version: "3.9"

services:
  backend:
    build: .
    container_name: game-tracker-backend
    ports:
      - "${PORT}:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - CHROME_BIN=/usr/bin/chromium
    volumes:
      - .:/app
      - /app/node_modules

    command: ["npm", "start"]
    # command: ["tail", "-f", "/dev/null"]
  client:
    build:
      context: ./client
    container_name: game-tracker-client
    ports:
      - "${CLIENT_PORT}:3001"
    env_file:
      - .env
    environment:
      VITE_API_BASE_URL: ${VITE_API_BASE_URL}
      NODE_ENV: "production"
    depends_on:
      - backend
    volumes:
      - ./client:/app
      - /app/node_modules

    # command: ["tail", "-f", "/dev/null"]
    command: sh -c "npm run build && npm run start"

networks:
  default:
    driver: bridge
