version: "3.9"

services:
  backend:
    build: .
    container_name: game-tracker-backend
    ports:
      - "${PORT}:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
      - /app/node_modules

  client:
    build:
      context: ./client
    container_name: game-tracker-client
    ports:
      - "${CLIENT_PORT}:3001"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - VITE_API_BASE_URL= ${VITE_API_BASE_URL}
    depends_on:
      - backend
    volumes:
      - ./client:/app
      - /app/node_modules

    # command: ["tail", "-f", "/dev/null"]
    command: ["npm", "start"]

networks:
  default:
    driver: bridge
